const mongoose = require('mongoose');

const speechSessionSchema = new mongoose.Schema({
  // Links this practice session to the specific user who recorded it
  userId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    required: true 
  },
  
  // Tracks whether the AI evaluated this in English or Filipino
  language: {
    type: String,
    enum: ['English', 'Filipino'],
    default: 'English',
    required: true
  },

  // Stores the physical file location
  audioPath: { 
    type: String, 
    required: true 
  },
  
  // Needed for the AI Logs "Audio Length" column
  durationSeconds: {
    type: Number,
    default: 0
  },

  // AI Processing Status
  status: {
    type: String,
    enum: ['Pending', 'Completed', 'Failed'],
    default: 'Pending'
  },

  // --- SMART ROUTING DATA ---
  // Tells MongoDB to link this session to specific challenges/scripts
  challengeData: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Challenge' 
  },
  scriptData: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Script'    
  },

  // --- AI EVALUATION METRICS ---
  // Reverted back to paceScore to match Flutter!
  paceScore: { 
    type: Number, 
    default: 0 
  },
  clarityScore: { 
    type: Number, 
    default: 0 
  },
  energyScore: { 
    type: Number, 
    default: 0 
  },
  overallScore: { 
    type: Number, 
    default: 0 
  },

  // The actual text of what they said
  transcription: { 
    type: String, 
    default: "No transcription available." 
  },
  
  // The specific text feedback generated by the AI
  aiFeedback: {
    type: String,
    default: "AI is still processing or failed to generate feedback."
  }

}, { 
  timestamps: true 
});

module.exports = mongoose.model('SpeechSession', speechSessionSchema);